# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b756f26c134f6c127b7f1f665ad995b516e893c90fd896c41e5edc00af13c09603ca9382e8eb7b7f19d5188a924a83a8de90846d4bf7fcb4bb6bdd1831d5bb9d

test:
  secret_key_base: 1033e26522a9e17390e8753d30dd90977a77673cd10b09724f5918b2466b127900e948ed6ee7aeaed26caef9a78386994dbddc97da8a1956690dfbc9cae63f25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
